management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
          - shutdown
          - beans
          - threaddump
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true



spring:
  application:
    name: util
  data:
    mongodb:
      uri: ${MONGO}
      port: 27017
      database: library
