logging:
  file: log/log.log
  level:
    root: INFO
    org:
      springframework:
        security: WARN
        boot:
          autoconfigure: INFO
        data.mongodb.core.MongoTemplate: INFO
server:
  port: 8080
  error:
    whitelabel:
      enabled: false


management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
          - shutdown
          - beans
          - threaddump
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true


spring:
  application:
    name: backend
  data:
    mongodb:
      uri: ${MONGO}
      port: 27017
      database: library

security:
  oauth2:
    resource:
      tokenInfoUri: http://oauth-server:8081/oauth/check_token