# Our certificate settings for enabling JWT tokens
jwt:
  certificate:
    store:
      file: classpath:/certificate/jwt.jks
      password: password
    key:
      alias: jwt
      password: password

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
          - shutdown
          - beans
          - threaddump
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true



spring:
  application:
    name: oauth-server
  data:
    mongodb:
      uri: ${MONGO}
      port: 27017
      database: library

logging:
  #  file: log/log.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO